config/routes.rb
Gomin::Application.routes.draw do

	resources :problems do
		member do
			post 'like'
			post 'dislike'
		end
	end

  root :to => 'main#index'
end

app/models/problem.rb
# encoding : UTF-8
class Problem < ActiveRecord::Base
  attr_accessible :title, :content

	validates :content, :presence => { :messsage => "내용을 입력해 주십시오" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController

	def create
		@problem = Problem.new(params[:problem])

		if @problem.save
		else
			flash[:notice] = "save failed #{@problem.errors.full_messages}"
		end

		redirect_to root_path
	end

	def like 
		@problem = Problem.find(params[:id]) 
		@problem.increment!(:like)
	end 

	def dislike
		@problem = Problem.find(params[:id]) 
		@problem.increment!(:dislike)

#		render :update do |page|
#			page.replace dom_id(@problem), :partial => 'problem', :locals => { :problem => @problem }
#		end
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_messages
		fl = flash[:notice]
		flash[:notice] = nil
		fl
	end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= SiteName %></title>
	<meta name="viewport" content="initial-scale=1.0; user-scalable=yes; minimum-scale=1.0; maximum-scale=1.0" /> 
	<meta name="apple-mobile-web-app-capable" content="yes" />
	 
	<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="flash_messages">
    <%= flash_messages %>
  </div>

  <div id="header">
		<div class="site_name">
			<%# link_to "거기누구없소?", root_path %>
			<%= link_to "Anybodyhear.me?", root_path %>
		</div>
  </div>

  <div id="section">
    <%= yield %>
  </div>

  <div id="footer">
		<div class="header_link">
			<a id="header_link" style="display:none" href="#top">TOP</a>
		</div>
 	</div>
 </div>

</body>
</html>

<script type="text/javascript">
	document.addEventListener("touchmove", touchMove, false);
	document.addEventListener("scroll", scroll, false);
	
	function touchMove(event) {
		$("#header_link").show(); 
	};

	function scroll(event) {
		if(window.pageYOffset == 0) $("#header_link").hide();
	};
</script>

app/views/main/index.html.erb
<div class="form_wrapper">
	<div class="desc">
		지금 당신의 고민을 등록하세요.
	</div>
	<%= form_for Problem.new do |f| %>
		<div class="field">
			<%= f.text_area :content, :class => "text", :rows => 5 ,:autofocus => :true %>
		</div>
		<div class="actions">
			<%= f.submit("고민등록") %>
		</div>
	<% end %>
</div>

<ul class="problems best">
	<div class="desc blue">
		고민이다. BEST
	</div>
	<% collection = Problem.find(:all, :order => "like desc", :limit => 3) %>
	<%= render :partial => '/problems/problem', :collection => collection %>
</ul>

<ul class="problems best">
	<div class="desc red">
		고민아니다. BEST
	</div>
	<% collection = Problem.find(:all, :order => "dislike desc", :limit => 3) %>
	<%= render :partial => '/problems/problem', :collection => collection %>
</ul>

<ul class="problems">
	<div class="desc">
		최신 고민들
	</div>
	<% collection = Problem.find(:all, :order => "id desc") %>
	<%= render :partial => '/problems/problem', :collection => collection %>
</ul>

app/views/problems/_problem.html.erb
<%= content_tag_for :li, problem do %>
	<div class="content">
		<%= truncate(problem.content.html_safe, :length => 110) %>
	</div>
	<div class="created_at">
		<%= "#{time_ago_in_words(problem.created_at)} ago" %>
	</div>
	<div class="actions <%= 'last' if Problem.first == problem %>">
		<div class="action blue">
			<%= link_to "고민이다. #{problem.like unless problem.like.zero?}", like_problem_path(problem), :method => :post, :remote => true %>
		</div>
		<div class="action middle red">
			<%= link_to "고민아니다. #{problem.dislike unless problem.dislike.zero?}", dislike_problem_path(problem), :method => :post, :remote => true %>
		</div>
		<div class="action">
			<%= link_to "댓글달기", "" %>
		</div>
	</div>
<% end %>

app/views/problems/dislike.js.erb
$('#<%= dom_id(@problem) %>').replaceWith('<%= escape_javascript((render :partial => "problem", :locals => {:problem => @problem})) %>');

app/views/problems/like.js.erb
$('#<%= dom_id(@problem) %>').replaceWith('<%= escape_javascript((render :partial => "problem", :locals => {:problem => @problem})) %>');